apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating BuildConfigs with jenkinsPipelineStrategy."
    tags: ""
parameters:
- name: "GIT_URL"
  displayName: "Git URL"
  description: "URL to git source repository containing Jenkinsfile. (e.g. https://github.com/tnozicka/jboss-eap-quickstarts.git)"
  required: true
- name: "GIT_REF"
  displayName: "Git Reference"
  description: "Git reference. (branch, ...)"
  value: "master"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: nodejs-ex-pipeline
    labels:
      application: nodejs-ex
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-ex-dev", "namespace": "", "kind": "DeploymentConfig"},{"name": "nodejs-ex-test", "namespace": "", "kind": "DeploymentConfig"},{"name": "nodejs-ex-prod", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
      - type: ConfigChange
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: .openshift-ci_cd/Jenkinsfile
    source:
      type: git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}